#!/usr/bin/python

import sqlite3

conn = sqlite3.connect('tr-torrent.db')
print "Opened database successfully"

conn.execute('''CREATE TABLE IF NOT EXISTS TROCKER
      (ID INTEGER PRIMARY KEY AUTOINCREMENT,
      TID              INT      NOT NULL,
      CATEGORY         TEXT     NOT NULL,
      LEECHERS         TEXT     NOT NULL,
      SEEDERS          TEXT     NOT NULL,
      RANKED           TEXT     NOT NULL,
      PUBDATE          TEXT     NOT NULL,
      TITLE            TEXT     NOT NULL,
      DOWNLOAD         TEXT     NOT NULL,
      INFO_PAGE         TEXT     NOT NULL,
      EPISODE_INFO      TEXT     NOT NULL,
      SIZE             TEXT     NOT NULL);''')
postid=56465
cur = conn.cursor()
cur.execute("select id from TROCKER where tid=?", (postid,))
data = cur.fetchall()
print data
if data :
   print 'found'
else:

   print ' not found'
#data={}
#
#data['tid']="56342"
#data['category']='TV HD Episodes'
#data['leechers']=20
#data['seeders']=30
#data['ranked']=1
#data['pubdate']='2017-04-16 14:40:19 +0000'
#data['title']='soup.title.text'
#data['download']='tamilmagnet'
#data['info_page']='http://test.rk.com'
#data['episode_info']='tstest'
#data['size']=467749940
#
##row=[data]
#row= [ data['tid'],data['category'],data['leechers'],data['seeders'],data['ranked'],data['pubdate'],data['title'],data['download'],data['info_page'],data['episode_info'],data['size'] ]
#
#query="INSERT INTO TROCKER VALUES (null,?,?,?,?,?,?,?,?,?,?,?)"
#conn.execute(query,row)
#conn.commit()
conn.close()
